# Generated by Django 4.0.3 on 2022-03-18 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vote_brands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='about',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='socialmedialink',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.contactsubject'),
            preserve_default=False,
        ),
    ]
