# Generated by Django 4.0.3 on 2022-03-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_vote_vote_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_brands',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.votebrand'),
        ),
    ]
