# Generated by Django 4.0.3 on 2022-03-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_vote_vote_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votebrand',
            name='subtitle',
        ),
    ]
